### ISSUE TITLE
Error about ppocrlabel, when start ppocrlabl

### ISSUE THREAD

**Issue by nam157** [PaddlePaddle/PaddleOCR#12522] opened 2024-05-28 08:50 UTC
#### 问题描述 / Problem Description
```bash
Traceback (most recent call last):
  File "PPOCRLabel.py", line 3461, in <module>
    sys.exit(main())
  File "PPOCRLabel.py", line 3448, in main
    app, _win = get_main_app(sys.argv)
  File "PPOCRLabel.py", line 3436, in get_main_app
    win = MainWindow(
  File "PPOCRLabel.py", line 148, in __init__
    result = self.table_ocr(
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 766, in __call__
    res, _ = super().__call__(
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppstructure/predict_system.py", line 129, in __call__
    res, table_time_dict = self.table_system(
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_table.py", line 86, in __call__
    structure_res, elapse = self._structure(copy.deepcopy(img))
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_table.py", line 109, in _structure
    structure_res, elapse = self.table_structurer(copy.deepcopy(img))
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppstructure/table/predict_structure.py", line 120, in __call__
    data = transform(data, self.preprocess_op)
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/namnguyen/miniconda3/envs/paddle/lib/python3.8/site-packages/paddleocr/ppocr/data/imaug/operators.py", line 94, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (213,488,4) (1,1,3)
```

#### 运行环境 / Runtime Environment
ubuntu
paddleocr                 2.7.3                    pypi_0    pypi
paddlepaddle              2.6.1                    pypi_0    pypi

**Comment by nam157** [comment] 2024-05-28 08:50
paddleocr                 2.7.3                    pypi_0    pypi
paddlepaddle              2.6.1                    pypi_0    pypi

**Comment by GreatV** [comment] 2024-05-28 09:17
https://github.com/PaddlePaddle/PaddleOCR/blob/92c59844f7d0c698e5a9a498399ec53a662e9a9f/paddleocr.py#L548

try change this line to:

```
return cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
```

**Comment by GreatV** [comment] 2024-05-28 09:21
Duplicate of #10748

**Closed** 2024-05-29 11:25 UTC
