### ISSUE TITLE
train warning

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#10298] opened 2023-07-05 03:58 UTC
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubantu 
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：paddle develop  0.0.0.post116

- 运行指令/Command Code：
- 完整报错/Complete Error Message：
一直有好多这种警告
I0705 11:55:13.443581 28582 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.

**Comment by GreatV** [comment] 2023-07-05 12:47
Duplicate of #10295

**Closed** 2023-07-07 11:20 UTC

**Comment by laishenghui** [comment] 2024-02-26 09:43
改动源码可以解决，调试发现报错代码位于PaddleOCR-release-2.6\tools\program.py第345行，做如下修改可以消除警告
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/81606481/f694b778-e2e6-4fdc-994d-0bb8fc19939c)
