### ISSUE TITLE
如何解决印章检测文件中配置问题

### ISSUE THREAD

**Issue by sadays22** [PaddlePaddle/PaddleOCR#13564] opened 2024-08-01 06:30 UTC
已线下沟通，此处close

_Originally posted by @tink2123 in https://github.com/PaddlePaddle/PaddleOCR/issues/11986#issuecomment-2078950627_

**Comment by GreatV** [comment] 2024-08-01 06:43
Duplicate of #13563

**Closed** 2024-08-01 06:43 UTC
