### ISSUE TITLE
CPU版本下的报错信息：`Segmentation fault` is detected by the operating system

### ISSUE THREAD

**Issue by chenxi510158746** [PaddlePaddle/PaddleOCR#12075] opened 2024-05-08 09:54 UTC
- System Environment：Linux（centos 7.9）
- Paddle Version：2.6.1
- PaddleOCR Version：2.7.3
- Command Code：paddleocr --image_dir /data/software/ppocr_img/imgs/11.jpg --det_model_dir /data/software/model --use_angle_cls true --use_gpu false
- Complete Error Message：

> C++ Traceback (most recent call last):
> 0   inflateReset2
> Error Message Summary:
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1715161768 (unix time) try "date -d @1715161768" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 3197862 (TID 0x7f7f29a461c0) from PID 0 ***]
> Segmentation fault (core dumped)

**Comment by GreatV** [comment] 2024-05-08 13:28
试试paddlepaddle2.5

**Comment by chenxi510158746** [comment] 2024-05-09 01:56
> 试试paddlepaddle2.5

谢谢！降到2.5版本 可以使用了

**Comment by GreatV** [comment] 2024-05-09 02:00
Duplicate of https://github.com/PaddlePaddle/PaddleOCR/issues/11597

**Closed by GreatV** 2024-05-09 02:00 UTC

**Comment by tppqt** [comment] 2024-05-09 06:27
你好，我用GPU运行PaddleOCR也报这个错
ubuntu20
cuda11.8
paddlepaddle-gpu2.4.2.post117和paddlepaddle-gpu2.5.0.post118都试过了不行
torch2.2.2+cu118
torchvision0.17.2+cu118

我想用yolov8+paddleocr识别视频里面的物体再识别文字，用GPU加速报这个错
![WechatIMG1404](https://github.com/PaddlePaddle/PaddleOCR/assets/19279148/505b8269-15ca-4492-96e3-dbbb7a54335c)
然后paddleocr配置的参数如下
![WechatIMG1403](https://github.com/PaddlePaddle/PaddleOCR/assets/19279148/e1050f2d-537d-4c40-bef4-e07cd2b4674b)

**Comment by GreatV** [comment] 2024-05-09 06:41
@tppqt 麻烦提供一个最小可复现代码

**Comment by dixyes** [comment] 2024-08-20 12:28
```bash
python -m venv venv
. ./venv/bin/activate
pip install wheel setuptools
pip install paddlepaddle==2.6.1 paddleocr
cat > some.py <<EOF
import os,sys

from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch")
result = ocr.ocr("some.png", cls=True)

print(result)
EOF
python some.py
```
